---
title: "SIR simulation for CZECHIA confirmed cases 2019-nCoV"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    
    theme: simplex
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared
# by all users of the dashboard
library(deSolve)
library(shinydashboard)
library(flexdashboard)
library(DT)


df = rjson::fromJSON(file="https://api.apify.com/v2/key-value-stores/K373S4uCFR9W1K8ei/records/LATEST?disableRedirect=true")

tdf2 <- data.frame(matrix(unlist(df$infectedDaily), nrow=length(df$infectedDaily), byrow=T))
tdf2$X1 <- as.numeric(as.character(tdf2$X1))
tdf2$X2 <- as.Date(as.character(tdf2$X2))
tdf2 <- tdf2[36:nrow(tdf2),]
names(tdf2) <- c("Pocet", "Den")

inf <- tdf2[tdf2$Pocet != 0, ]
Infected <- inf$Pocet
Day <- 1:(length(Infected))
N <- 10000000 # population of mainland china

old <- par(mfrow = c(1, 2))

SIR <- function(time, state, parameters) {
  par <- as.list(c(state, parameters))
  with(par, {
    dS <- -beta/N * I * S
    dI <- beta/N * I * S - gamma * I
    dR <- gamma * I
    list(c(dS, dI, dR))
  })
}

init <- c(S = N-Infected[1], I = Infected[1], R = 0)
RSS <- function(parameters) {
  names(parameters) <- c("beta", "gamma")
  out <- ode(y = init, times = Day, func = SIR, parms = parameters)
  fit <- out[ , 3]
  sum((Infected - fit)^2)
}

Opt <- optim(c(0.5, 0.5), RSS, method = "L-BFGS-B", lower = c(0, 0), upper = c(1, 1)) # 

Opt_par <- setNames(Opt$par, c("beta", "gamma"))

t <- 1:80 # time in days
fit <- data.frame(ode(y = init, times = t, func = SIR, parms = Opt_par))
col <- 1:3 # colour



```

Column
--------------------------------------------------
```{r}


plot(Day, Infected, type ="b")
title("Confirmed Cases 2019-nCoV Czechia", outer = TRUE, line = -2)
plot(Day, Infected, log = "y")
abline(lm(log10(Infected) ~ Day))
title("Confirmed Cases 2019-nCoV Czechia", outer = TRUE, line = -2)



matplot(fit$time, fit[ , 2:4], type = "l", xlab = "Day", ylab = "Number of subjects", lwd = 2, lty = 1, col = col)
title("SIR model 2019-nCoV Czechia", outer = TRUE, line = -2)

matplot(fit$time, fit[ , 2:4], type = "l", xlab = "Day", ylab = "Number of subjects", lwd = 2, lty = 1, col = col, log = "y")

points(Day, Infected)
legend("bottomright", c("Susceptibles", "Infecteds", "Recovereds"), lty = 1, lwd = 2, col = col, inset = 0.05)
title("SIR model 2019-nCoV Czechia", outer = TRUE, line = -2)



```


```{r}

par(old)
 

 
days <- fit[fit$I == max(fit$I), "I", drop = FALSE] # height of pandemic
R0 <- setNames(Opt_par["beta"] / Opt_par["gamma"], "R0")
max_infected <- max(fit$I)
sc <- max_infected / 5
maxD <- max(fit$I) * 0.02 # max deaths with supposed 2% fatality rate
ic <-  max_infected * 0.06

simdf <- data.frame(R0, sc, ic, days)
renderTable({
  simdf
})
```

